version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'

  db:
    image: postgres:13.3
    environment:
      - POSTGRES_DB=example-db
      - POSTGRES_USER=example-user
      - POSTGRES_PASSWORD=example-pass
    ports:
      - "5432:5432"

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "5000:8080"
